# Generated by Django 6.0.5 on 2026-05-08 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accessdomain_identitysession_presencepolicy_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='operational_state',
            field=models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('ACTIVE', 'Active'), ('AT_RISK', 'At Risk'), ('ACADEMIC_WARNING', 'Academic Warning'), ('FINANCIAL_HOLD', 'Financial Hold'), ('DISCIPLINARY_REVIEW', 'Disciplinary Review'), ('PLACEMENT_READY', 'Placement Ready'), ('GRADUATED', 'Graduated'), ('ALUMNI', 'Alumni'), ('INACTIVE', 'Inactive')], default='ONBOARDING', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='reputation_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='student',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='StateChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('old_state', models.CharField(max_length=30)),
                ('new_state', models.CharField(max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentOperationalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event_type', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical'), ('SYSTEM', 'System')], default='NORMAL', max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=20)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acted_events', to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_events', to='accounts.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'event_type'], name='accounts_st_student_1b42f5_idx'), models.Index(fields=['student', 'timestamp'], name='accounts_st_student_172f05_idx'), models.Index(fields=['correlation_id'], name='accounts_st_correla_1da1bb_idx')],
            },
        ),
    ]
