# Generated by Django 6.0.5 on 2026-05-08 12:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_bio_student_operational_state_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('achievement_type', models.CharField(choices=[('CERTIFICATION', 'Course Certification'), ('DEANS_LIST', "Dean's List Placement"), ('TOPPER', 'Semester Topper'), ('RESEARCH', 'Research Contribution'), ('VOLUNTEER', 'Service Recognition')], max_length=30)),
                ('issued_at', models.DateField()),
                ('verification_hash', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuccessConfidenceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('score', models.IntegerField()),
                ('reason_breakdown', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_history', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuccessSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('signal_type', models.CharField(choices=[('ATTENDANCE_DECAY', 'Attendance Decay'), ('ENGAGEMENT_SPIKE', 'Engagement Spike'), ('GRADE_VOLATILITY', 'Grade Volatility'), ('CONSISTENCY_AWARD', 'Consistency Award'), ('SOCIAL_ISOLATION', 'Social Isolation Risk'), ('FINANCIAL_STRESS', 'Financial Stress Signal')], max_length=30)),
                ('weight', models.CharField(choices=[('POSITIVE', 'Positive Impact'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative Impact'), ('CRITICAL', 'Critical/Actionable')], default='NEUTRAL', max_length=20)),
                ('confidence_delta', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success_signals', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterventionOrchestration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Trigger'), ('ACTIVE', 'Active Intervention'), ('RESOLVED', 'Resolved/Successful'), ('ESCALATED', 'Escalated to Management'), ('FAILED', 'Intervention Failed')], default='PENDING', max_length=20)),
                ('action_plan', models.TextField()),
                ('resolution_notes', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to='accounts.faculty')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='accounts.student')),
                ('trigger_signal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.successsignal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
