# Generated by Django 6.0.5 on 2026-05-08 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_academicachievement_successconfidencehistory_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('goal_type', models.CharField(choices=[('GPA', 'Grade Point Average'), ('CREDIT', 'Credit Completion'), ('ATTENDANCE', 'Attendance Threshold'), ('SKILL', 'Skill Mastery Level')], max_length=20)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('relation_type', models.CharField(choices=[('MENTOR', 'Academic Mentor'), ('ADVISOR', 'Institutional Advisor'), ('PEER_COACH', 'Peer Success Coach')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('peer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coaching_peers', to='accounts.student')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_network', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
