# Generated by Django 6.0.5 on 2026-05-08 18:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_placementbenchmark_systemrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplanationTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.UUIDField(null=True)),
                ('trace_data', models.JSONField(help_text="Weighted factors: {'attendance': 0.4, 'grades': 0.6}")),
                ('rationale', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
