# Generated by Django 6.0.5 on 2026-05-08 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_explanationtrace'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('engine_name', models.CharField(max_length=100)),
                ('snapshot_data', models.JSONField()),
                ('last_recalculated', models.DateTimeField(auto_now=True)),
                ('freshness_state', models.CharField(default='STALE', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
