# Generated by Django 6.0.5 on 2026-05-08 18:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_intelligencemetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalDomainEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('ATTENDANCE_DROP', 'Attendance Drop'), ('GPA_CHANGE', 'GPA Change'), ('GOAL_COMPLETE', 'Goal Completed'), ('INTERVENTION_TRIGGER', 'Intervention Triggered'), ('BEHAVIORAL_ANOMALY', 'Behavioral Anomaly')], max_length=50)),
                ('context', models.JSONField(help_text='Event metadata and payloads')),
                ('actor', models.CharField(default='SYSTEM', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_events', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
