# Generated by Django 6.0.5 on 2026-05-08 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_policydefinition_institutionaloverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGraphNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('SUBJECT', 'Subject'), ('SKILL', 'Skill'), ('CAREER_PATH', 'Career Path'), ('BEHAVIOR', 'Behavior')], max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraphEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('edge_type', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=1.0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='accounts.knowledgegraphnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='accounts.knowledgegraphnode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
