# Generated by Django 6.0.5 on 2026-05-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_knowledgegraphnode_knowledgegraphedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='successsignal',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
