# Generated by Django 6.0.5 on 2026-05-09 07:06

import accounts.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_successsignal_is_resolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityInteractionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action', models.CharField(max_length=100)),
                ('surface', models.CharField(max_length=50)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_logs', to='accounts.student')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IdentityTelemetrySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('trust_score', models.IntegerField(default=50)),
                ('confidence_score', models.IntegerField(default=50)),
                ('presence_state', models.CharField(default='OFFLINE', max_length=50)),
                ('active_device', models.CharField(blank=True, max_length=100)),
                ('signals_summary', models.JSONField(default=dict)),
                ('confidence_layer', models.CharField(default='MODERATE', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_snapshots', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentOperationalPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('focus_mode', models.BooleanField(default=False)),
                ('high_fidelity_ui', models.BooleanField(default=True)),
                ('notification_governance', models.JSONField(default=accounts.models.default_notification_governance)),
                ('theme_intelligence', models.CharField(default='ADAPTIVE', max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
