# Generated by Django 6.0.5 on 2026-05-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_identityinteractionlog_identitytelemetrysnapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentoperationalpreference',
            name='high_fidelity_ui',
        ),
        migrations.AddField(
            model_name='studentoperationalpreference',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentoperationalpreference',
            name='theme_accent',
            field=models.CharField(default='#FF6B00', max_length=7),
        ),
        migrations.AddField(
            model_name='studentoperationalpreference',
            name='ui_density',
            field=models.CharField(choices=[('COMPACT', 'Compact'), ('COZY', 'Cozy'), ('RELAXED', 'Relaxed')], default='COZY', max_length=20),
        ),
    ]
