# Generated by Django 6.0.5 on 2026-05-09 08:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_studentoperationalpreference_high_fidelity_ui_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrelationship',
            name='engagement_frequency',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='supportrelationship',
            name='intervention_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supportrelationship',
            name='relationship_health',
            field=models.CharField(choices=[('OPTIMAL', 'Optimal'), ('STABLE', 'Stable'), ('AT_RISK', 'At Risk')], default='OPTIMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='supportrelationship',
            name='responsiveness_score',
            field=models.IntegerField(default=95),
        ),
        migrations.AddField(
            model_name='supportrelationship',
            name='trust_level',
            field=models.CharField(choices=[('STRONG', 'Strong'), ('MODERATE', 'Moderate'), ('LOW', 'Low')], default='STRONG', max_length=20),
        ),
        migrations.CreateModel(
            name='SupportCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Recovery'), ('FINANCIAL', 'Financial Stability'), ('WELLNESS', 'Mental Wellness'), ('PLACEMENT', 'Career Readiness')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Intervention'), ('RESOLVED', 'Issue Resolved'), ('ESCALATED', 'Escalated to HOD')], default='ACTIVE', max_length=20)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical Priority'), ('HIGH', 'High Priority'), ('NORMAL', 'Standard Priority')], default='NORMAL', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_cases', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('INTERVENTION', 'Institutional Intervention'), ('MENTOR_MEETING', 'Mentor Guidance Session'), ('WELLNESS_CHECK', 'Wellness Verification'), ('ESCALATION', 'Support Escalation')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.supportrelationship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_timeline', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
