# Generated by Django 6.0.5 on 2026-05-07 05:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_state',
            field=models.CharField(choices=[('PENDING', 'Pending Analysis'), ('ANALYZED', 'Analyzed'), ('FLAGGED', 'Flagged (Risk)')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='fraud_signals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='learning_signals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='needs_attention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='priority_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='review_duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='review_state',
            field=models.CharField(choices=[('UNTOUCHED', 'Untouched'), ('IN_PROGRESS', 'In Progress'), ('REVIEWED', 'Reviewed'), ('RETURNED', 'Returned to Student')], default='UNTOUCHED', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Risk')], default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='submission',
            name='rubric_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='voice_feedback',
            field=models.FileField(blank=True, null=True, upload_to='feedback/voice/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='workflow_state',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=20),
        ),
        migrations.CreateModel(
            name='EvaluationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('SUBMISSION_UPLOADED', 'Submission Uploaded'), ('AI_ANALYSIS_COMPLETED', 'AI Analysis Completed'), ('REVIEW_STARTED', 'Review Started'), ('RISK_FLAGGED', 'Risk Flagged'), ('FEEDBACK_SENT', 'Feedback Sent'), ('GRADE_LOCKED', 'Grade Locked')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.faculty')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='lms.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
