# Generated by Django 6.0.4 on 2026-04-30 16:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('faculty_snapshot_name', models.CharField(max_length=255)),
                ('subject_snapshot_name', models.CharField(max_length=255)),
                ('session_type', models.CharField(choices=[('REGULAR', 'Regular (Timetable)'), ('EXTRA', 'Extra Class'), ('REPLACEMENT', 'Replacement Class')], default='REGULAR', max_length=20)),
                ('status', models.CharField(choices=[('LIVE', 'Live 🔴'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('LOCKED', 'Audited & Locked')], default='LIVE', max_length=15)),
                ('mode', models.CharField(choices=[('QR', 'Dynamic QR Scan'), ('MANUAL', 'Manual Marking'), ('HYBRID', 'Hybrid Mode')], default='QR', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('expected_count', models.IntegerField(default=0)),
                ('present_count', models.IntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=0)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('session_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_sessions', to='accounts.faculty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], default='PRESENT', max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='operations.attendancesession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperationsActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QRIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rotating_token', models.UUIDField(default=uuid.uuid4)),
                ('nonce', models.CharField(blank=True, max_length=64, null=True)),
                ('issued_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('building', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.IntegerField()),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('DUPLICATE', 'Duplicate Scan'), ('INVALID', 'Invalid QR'), ('NOT_ENROLLED', 'Not Enrolled'), ('EXPIRED', 'Expired QR')], max_length=20)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('session_version', models.PositiveIntegerField(default=0)),
                ('raw_data', models.TextField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='operations.attendancesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
            options={
                'unique_together': {('faculty', 'subject', 'semester', 'college')},
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('section', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
            ],
            options={
                'ordering': ['-academic_year', '-version'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_type', models.CharField(choices=[('REGULAR', 'Regular Class'), ('LAB', 'Laboratory'), ('TUTORIAL', 'Tutorial'), ('SEMINAR', 'Seminar')], default='REGULAR', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.subjectassignment')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.room')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='operations.timetable')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlotInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('READY', 'Ready'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed/Cancelled')], default='SCHEDULED', max_length=20)),
                ('expected_students', models.IntegerField(default=0)),
                ('actual_students', models.IntegerField(default=0)),
                ('timetable_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='operations.timetableslot')),
            ],
            options={
                'ordering': ['-date', 'timetable_slot__start_time'],
                'unique_together': {('timetable_slot', 'date')},
            },
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='slot_instance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='operations.timetableslotinstance'),
        ),
        migrations.CreateModel(
            name='EnrollmentMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('section', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_enrollments', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'semester', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='SessionEnrollmentSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_snapshot', to='operations.attendancesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
    ]
