# Generated by Django 6.0.4 on 2026-05-01 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='snapshot_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Immutable snapshot of context at start time'),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='confidence_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='device_type',
            field=models.CharField(default='MOBILE_APP', max_length=50),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='proxy_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='scan_source',
            field=models.CharField(default='QR_DYNAMIC', max_length=50),
        ),
        migrations.CreateModel(
            name='ExecutionControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('grace_minutes', models.IntegerField(default=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('LIVE', 'Live'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('trigger_mode', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], default='MANUAL', max_length=10)),
                ('version', models.PositiveIntegerField(default=0)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('slot_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='operations.timetableslotinstance')),
            ],
            options={
                'verbose_name_plural': 'Execution Control',
            },
        ),
        migrations.CreateModel(
            name='SessionStateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('from_state', models.CharField(max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('action_type', models.CharField(default='MANUAL', max_length=20)),
                ('trigger_source', models.CharField(default='ADMIN', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='operations.attendancesession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyWorklog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('total_sessions', models.IntegerField(default=0)),
                ('completed_sessions', models.IntegerField(default=0)),
                ('missed_sessions', models.IntegerField(default=0)),
                ('extra_sessions', models.IntegerField(default=0)),
                ('total_duration_minutes', models.IntegerField(default=0)),
                ('source_sessions', models.JSONField(default=list, help_text='IDs of sessions contributing to this log')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='accounts.faculty')),
            ],
            options={
                'unique_together': {('faculty', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cache_version', models.PositiveIntegerField(default=1)),
                ('last_rebuilt_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_cache', to='accounts.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.timetable')),
            ],
            options={
                'unique_together': {('student', 'subject', 'timetable')},
            },
        ),
    ]
