# Generated by Django 6.0.4 on 2026-04-30 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='subjectenrollment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='academics.subject'),
        ),
        migrations.AddIndex(
            model_name='subjectenrollment',
            index=models.Index(fields=['student', 'subject'], name='academics_s_student_87dee8_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectenrollment',
            index=models.Index(fields=['semester'], name='academics_s_semeste_530a6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectenrollment',
            unique_together={('student', 'subject', 'semester')},
        ),
    ]
