# Generated by Django 6.0.5 on 2026-05-08 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0004_academicachievement_successconfidencehistory_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.college')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentSkillMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('mastery_level', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('evidence_log', models.JSONField(blank=True, default=dict)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mastery', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='SubjectSkillMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('weight', models.IntegerField(default=50)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mappings', to='academics.skill')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mappings', to='academics.subject')),
            ],
            options={
                'unique_together': {('subject', 'skill')},
            },
        ),
    ]
